version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 20
    groups:
      python-dependencies:
        patterns: ['*']

  - package-ecosystem: "maven"
    directory: "/java"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 20
    groups:
      java-dependencies:
        patterns: ['*']

  - package-ecosystem: "bundler"
    directory: "/compare"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 20
    groups:
      ruby-dependencies:
        patterns: ['*']

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
