name: embed-encode

channels:
  - conda-forge

dependencies:
  - python=3.11
  - cheap_repr
  - ipykernel
  - numpy
  - openai
  - requests
  - tabulate

  # Development tools
  - flake8
  - mypy
  - pyright
