name: embed-encode

channels:
  - conda-forge

dependencies:
  - python=3.11
  - cheap_repr
  - ipykernel
  - numpy
  - openai
  - requests
  - tabulate

  # For openai.embeddings_utils (move above if used directly)
  - matplotlib
  - pandas
  - plotly
  - scikit-learn
  - scipy
  - tenacity

  # Development tools
  - flake8
  - mypy
  - pyright
