name: "Rubocop"

on: [push, pull_request]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
    defaults:
      run:
        working-directory: compare

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    - name: Install dependencies
      run: bundle install

    - name: Rubocop run
      run: |
        bundle exec rubocop --require code_scanning --format progress --format CodeScanning::SarifFormatter -o rubocop.sarif

    - name: Upload Sarif output
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: compare/rubocop.sarif
