name: "Rubocop"

on: [push, pull_request]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        working-directory: ./compare

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    # FIXME: Add to Gemfile instead of specifying it here.
    - name: Install Code Scanning integration
      run: bundle add code-scanning-rubocop --version 0.6.1 --skip-install

    - name: Install dependencies
      run: bundle install

    - name: Rubocop run
      run: |
        printf 'WORKING DIRECTORY: %s\n' "$(pwd)"  # FIXME: Remove after debugging.
        bash -c "
          bundle exec rubocop --require code_scanning --format CodeScanning::SarifFormatter -o rubocop.sarif
          [[ $? -ne 2 ]]
        "

    - name: Upload Sarif output
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: rubocop.sarif
